### ISSUE TITLE
Migro fails to install

### ISSUE THREAD

**Issue by rockshell** [uploadcare/pyuploadcare#297]
### Describe the bug

Hello.
We've got this issue from our user. Could you please take a look?
Here's the report part:

> Also tried using python3 that is bundled with ubuntu. 
`pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)` but when running `pip3 install uploadcare-migro` I get the following error:

```
Defaulting to user installation because normal site-packages is not writeable
Collecting uploadcare-migro
  Using cached uploadcare_migro-2.0.0.tar.gz (21 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-_02_wbvl/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
          builder = WheelBuilder(poetry)
        File "/tmp/pip-build-env-_02_wbvl/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/builders/wheel.py", line 62, in __init__
          super().__init__(poetry, executable=executable)
        File "/tmp/pip-build-env-_02_wbvl/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/builders/builder.py", line 55, in __init__
          self._meta = Metadata.from_package(self._package)
        File "/tmp/pip-build-env-_02_wbvl/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/metadata.py", line 58, in from_package
          with readme.open(encoding="utf-8") as f:
        File "/usr/lib/python3.10/pathlib.py", line 1119, in open
          return self._accessor.open(self, mode, buffering, encoding, errors,
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-prdew3g7/uploadcare-migro_0a043162fc4c47a0ad888b62e48932eb/README.md'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

Discussion took place here:  https://discord.com/channels/921297127517327412/1282906285871992832/1282906285871992832

Let us know if there's more information required.

**Comment by dmitry-mukhin** [comment]
1. it looks like it supposed to go to https://github.com/uploadcare/migro repo
2. ask the user to provide `project.toml`
